[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_project = "Bs5QoCadKbunU2oMbS7YEGwEjfyPfPYN1k4Td9z5WWmP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
